# Generated by Django 4.2.24 on 2025-09-29 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_date', models.DateField()),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('useful_life_years', models.IntegerField()),
                ('depreciation_method', models.CharField(blank=True, choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('DOUBLE_DECLINING', 'Double Declining Balance'), ('UNITS_OF_PRODUCTION', 'Units of Production')], help_text='Leave blank to use category default', max_length=20)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('NEEDS_REPAIR', 'Needs Repair')], default='GOOD', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISPOSED', 'Disposed'), ('SOLD', 'Sold'), ('LOST', 'Lost'), ('STOLEN', 'Stolen')], default='ACTIVE', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disposal_method', models.CharField(blank=True, choices=[('SALE', 'Sale'), ('TRADE', 'Trade-in'), ('DONATION', 'Donation'), ('SCRAP', 'Scrap'), ('LOSS', 'Loss/Theft')], max_length=20)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('useful_life_years', models.IntegerField(help_text='Default useful life in years for assets in this category')),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('DOUBLE_DECLINING', 'Double Declining Balance'), ('UNITS_OF_PRODUCTION', 'Units of Production')], default='STRAIGHT_LINE', max_length=20)),
                ('asset_account', models.CharField(help_text='Asset account code', max_length=50)),
                ('depreciation_account', models.CharField(help_text='Accumulated depreciation account code', max_length=50)),
                ('expense_account', models.CharField(help_text='Depreciation expense account code', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_date', models.DateField()),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('CORRECTIVE', 'Corrective Maintenance'), ('EMERGENCY', 'Emergency Repair'), ('UPGRADE', 'Upgrade'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_date', models.DateField()),
                ('service_provider', models.CharField(blank=True, max_length=200)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depreciation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(max_length=20)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('period_year', models.IntegerField(blank=True, null=True)),
                ('accumulated_depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('journal_entry_created', models.BooleanField(default=False)),
                ('journal_entry_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.asset')),
            ],
            options={
                'ordering': ['-depreciation_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
