# Generated by Django 4.2.24 on 2025-09-26 11:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        # Create Material model first
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_modifier_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('MULTIPLIER', 'Multiplier')], default='PERCENTAGE', max_length=20)),
                ('price_modifier_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('brand', 'name')},
        ),
        # Remove old constraints and indexes first
        migrations.RemoveIndex(
            model_name='servicevariant',
            name='service_var_service_6b7188_idx',
        ),
        migrations.AlterUniqueTogether(
            name='servicevariant',
            unique_together=set(),
        ),
        # Add material field
        migrations.AddField(
            model_name='servicevariant',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Optional material/brand specification (e.g., 3M, LLUMAR for tints)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_variants', to='services.material'),
        ),
        # Now add new constraints and indexes that reference material field
        migrations.AlterUniqueTogether(
            name='servicevariant',
            unique_together={('service', 'part', 'vehicle_class', 'material')},
        ),
        migrations.AddIndex(
            model_name='servicevariant',
            index=models.Index(fields=['service', 'part', 'vehicle_class', 'material'], name='service_var_service_428acf_idx'),
        ),
        migrations.AlterModelOptions(
            name='servicevariant',
            options={'ordering': ['service__name', 'part__name', 'vehicle_class__name', 'material__brand']},
        ),
    ]
