# Generated by Django 4.2.24 on 2025-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_material_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name='servicevariant',
            options={'ordering': ['service__name', 'part__name', 'vehicle_class__name']},
        ),
        migrations.RemoveIndex(
            model_name='servicevariant',
            name='service_var_service_428acf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='servicevariant',
            unique_together={('service', 'part', 'vehicle_class')},
        ),
        migrations.AddIndex(
            model_name='servicevariant',
            index=models.Index(fields=['service', 'part', 'vehicle_class'], name='service_var_service_6b7188_idx'),
        ),
        migrations.RemoveField(
            model_name='servicevariant',
            name='material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
