# Generated by Django 4.2.24 on 2025-09-26 11:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('services', '0003_remove_material_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVariantInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this inventory item is required for this service')),
                ('standard_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Standard quantity needed for this service', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('floor_price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional floor price when this inventory item is used', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_options', to='services.servicevariant')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_variant_options', to='inventory.sku')),
            ],
            options={
                'db_table': 'service_variant_inventory',
                'ordering': ['service_variant', 'sku__name'],
                'unique_together': {('service_variant', 'sku')},
            },
        ),
    ]
