# Generated by Django 4.2.24 on 2025-09-26 21:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional selling price per unit for inventory items', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
