# Generated by Django 4.2.24 on 2025-09-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('AUTO', 'Automatic Entry'), ('SALE', 'Sale Transaction'), ('PURCHASE', 'Purchase Transaction'), ('DEPRECIATION', 'Depreciation Entry'), ('DISPOSAL', 'Asset Disposal'), ('ADJUSTMENT', 'Adjustment Entry')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
    ]
