# Generated by Django 4.2.24 on 2025-09-26 11:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLineInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, help_text='Actual quantity consumed from inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Unit cost from inventory at time of consumption', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_consumed', models.BooleanField(default=False, help_text='Whether inventory has been deducted from stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='sales.jobline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_line_usages', to='inventory.sku')),
            ],
            options={
                'db_table': 'job_line_inventory',
                'ordering': ['job_line', 'sku__name'],
            },
        ),
    ]
