# Generated by Django 4.2.24 on 2025-09-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_job_line_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional for walk-in customers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Optional for unregistered vehicles', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='sales.vehicle'),
        ),
    ]
