# Generated by Django 4.2.24 on 2025-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_receipt_invoice_invoices_invoice_7778bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
