# Generated by Django 4.2.24 on 2025-10-11 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobline',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='Employees assigned to perform this service', related_name='assigned_job_lines', to=settings.AUTH_USER_MODEL),
        ),
    ]
