# Generated by Django 4.2.24 on 2025-10-11 08:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_service_variant_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0006_jobline_assigned_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCommissionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee who will receive commission', on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to=settings.AUTH_USER_MODEL)),
                ('service_variant', models.ForeignKey(blank=True, help_text='Service variant for this rate. Null means default rate for all services.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='services.servicevariant')),
            ],
            options={
                'db_table': 'employee_commission_rates',
                'ordering': ['employee', 'service_variant'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='employee_co_employe_0901ac_idx'), models.Index(fields=['service_variant', 'is_active'], name='employee_co_service_ecf7e6_idx')],
                'unique_together': {('employee', 'service_variant')},
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate used for calculation', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('service_amount', models.DecimalField(decimal_places=2, help_text='Service line amount used for commission calculation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PAYABLE', 'Payable'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', help_text='Commission status in workflow', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When commission was paid to employee', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference for commission payment', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee earning this commission', on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job associated with this commission', on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='sales.job')),
                ('job_line', models.ForeignKey(help_text='Specific job line this commission is for', on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='sales.jobline')),
                ('paid_by', models.ForeignKey(blank=True, help_text='User who processed commission payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='commissions_employe_cbaafc_idx'), models.Index(fields=['job', 'status'], name='commissions_job_id_829e69_idx'), models.Index(fields=['status', 'created_at'], name='commissions_status_eec601_idx')],
            },
        ),
    ]
