# Generated by Django 4.2.24 on 2025-10-14 15:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_employeecommissionrate_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Tip amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Payment status of the tip', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit')], help_text='Method used to pay the tip to employee', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When tip was paid to employee', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee receiving the tip', on_delete=django.db.models.deletion.PROTECT, related_name='tips_received', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job where tip was received', on_delete=django.db.models.deletion.PROTECT, related_name='tips', to='sales.job')),
                ('paid_by', models.ForeignKey(blank=True, help_text='User who processed tip payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_tips', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded the tip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tips',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='tips_employe_12b996_idx'), models.Index(fields=['job', 'employee'], name='tips_job_id_f6958b_idx'), models.Index(fields=['status', 'created_at'], name='tips_status_367e17_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount requested as advance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount approved (may differ from requested)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('available_commission', models.DecimalField(decimal_places=2, help_text='Available commission balance at time of request', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Advance payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit')], help_text='Payment method used', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('reason', models.TextField(help_text='Reason for requesting advance')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('payment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee requesting advance', on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, help_text='User who processed payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_advances', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Manager who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advance_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='advance_pay_employe_3f5cb5_idx'), models.Index(fields=['status', 'requested_at'], name='advance_pay_status_c874f3_idx')],
            },
        ),
    ]
