# Generated by Django 4.2.24 on 2025-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_tips_and_advances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('RECOVERED', 'Recovered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Advance payment status', max_length=20),
        ),
    ]
